### ISSUE TITLE
Error al hacer clic en algunas imágenes de la portada en el Home

### ISSUE THREAD

**Issue by mentorrolling** [antonellamercado/birdDomain#47]
![image](https://user-images.githubusercontent.com/68254100/108392503-8bb6c480-71f1-11eb-870f-492f2b905b7d.png)

**Comment by slipknokita** [comment]
Este problema ocurre cuando la latitud y longitud cargada en la base de datos desde el panel admin no corresponde a una latitud o longitud real, o no fue ingresado en el sistema de coordenadas correspondientes (deben ingresarse en grados decimales). Se modificó la latitud y longitud para el tour que presentaba problemas.
