### ISSUE TITLE
Pantalla administrador: Cuando voy a crear nuevo tour 

### ISSUE THREAD

**Issue by mentorrolling** [antonellamercado/birdDomain#48]
Si le doy clic por primera vez al botón crear Tour los campos están vacios para rellenar, pero si edito un tour existente y luego voy a dar clic al botón para crear uno nuevo, en los campos aparecen los datos del tour que edite antes.

**Comment by antonellamercado** [comment]
Pude reproducir el error siguiendo estos pasos:

- Click en boton Editar 
- Cerrar modal SIN editar
- Click boton crear tour

se guardaba el ID del tour q se abrio para editar y no se edito.


#Resuelto
